### ISSUE TITLE
Why codedamn is EXCLUDED from HACKTOBER-FEST-2021

### ISSUE THREAD

**Issue by kambojshalabh35** [codedamn/codedamn-hacktoberfest-projects#422]
![image](https://user-images.githubusercontent.com/71832334/136743188-8a63522c-e331-4701-9124-33bb94d45101.png)

I wanna to know the reason why?

**Comment by vinayvikram** [comment]
@kambojshalabh35 
I don't know the reason.
I am not from the CODEDAMN team..

But, It seems that hacktoberfest team has done some automation using bots to identify the repo's which are not following the rule and exclude them from the fest. They told that these exclusion can't be undo.

It may be that because of large numbers of unmerged PRs, this repo had been excluded.

I think, we should wait for the codedamn team to do something regarding this.
